# kind: pipeline
# name: default

# steps:
# - name:
#   image: mongo
#   detach: true

# - name: test
#   image: node:11.1-alpine
#   commands:
#     - npm install
#     - npm start &
#     - npm test

pipeline:
  realworld-mongo:
    image: mongo
    detach: true

  test:
    image: node:11.1-alpine
    commands:
      - npm install
      - npm start &
      - npm test
